#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    lightsensor,    sensorReflection)
#pragma config(Sensor, in5,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           Armmotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Clawmotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|* - Moving using controller - *|
verkefni 3.2
Foritið fjarstýringu þannig að hægt sé að stoppa róbot notið kóðan úr 3.hluta í verkefni 2
\*-----------------------------------------------------------------------------------------------*/

#include "../includes/headers/headers.h"
#include "../includes/functions/motor_encoder.inc"
task main()
{
	StartTask(Killswitch);//gets killswitch

 	bool turnarray[14] = {0,1,1,0,0,1,0,0,1,0,0,1,1,0};//if array 1 left if array 0 right
  for(int i = 0;i <= 14 ;i++)
  	{
  		EncoderReset();
  		Stop_Motors(1000);//stops for 1000 milliseconds
  		DriveEncoder(250);
  		EncoderTurn(90,turnarray[i]);

  }
  StopTask(Killswitch);
}
